apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-server
        image: vera5660/demucs-worker:latest
        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio:9000"
        - name: MINIO_USER
          value: "rootuser"
        - name: MINIO_PASSWD
          value: "rootpass123"
        