FROM python:3.7
LABEL MAINTAINER="isba1563@colorado.edu"
RUN  pip3 install --upgrade redis minio scikit-learn pandas xgboost pykafka 
WORKDIR /app
COPY    kafka_consumer.py .
CMD [ "python3", "kafka_consumer.py"]

