FROM python:3.7-alpine
LABEL MAINTAINER="isba1563@colorado.edu"
RUN apk add gcc libc-dev libffi-dev
RUN  pip3 install --upgrade redis minio pykafka pandas xgboost
WORKDIR /app
COPY    kafka_consumer.py .
CMD [ "python3", "kafka_consumer.py"]

