apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: isba1563/kafka-producer:latest
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MINIO_HOST
              value: "minio:9000"
            - name: MINIO_USER
              value: "rootuser"
            - name: MINIO_PASSWD
              value: "rootpass123"
            - name: KAFKA_HOST
              value: "kafka-app"
            - name: KAFKA_PORT
              value: "9092"
