FROM python:3.7-alpine
LABEL MAINTAINER="vera5660@colorado.edu"
RUN apk add gcc libc-dev libffi-dev
RUN  pip3 install --upgrade redis jsonpickle requests flask minio
WORKDIR /app
COPY    rest-server.py .
EXPOSE 5000
CMD [ "python3", "rest-server.py"]

